-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 14:40:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Diariodigital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Diariodigital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Diariodigital` DEFAULT CHARACTER SET utf8 ;
USE `Diariodigital` ;

-- -----------------------------------------------------
-- Table `Diariodigital`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diariodigital`.`usuario` (
  `id` INT NOT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `nick`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diariodigital`.`Anotacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diariodigital`.`Anotacoes` (
  `id` INT NOT NULL,
  `grenciamento` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `usuario_nick` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Anotacoes_usuario_idx` (`usuario_id` ASC, `usuario_nick` ASC) VISIBLE,
  CONSTRAINT `fk_Anotacoes_usuario`
    FOREIGN KEY (`usuario_id` , `usuario_nick`)
    REFERENCES `Diariodigital`.`usuario` (`id` , `nick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into  usuario(id, nick, senha)
values(1, "Pedro", "123456");
select *FROM  usuario;


