-- MySQL Script generated by MySQL Workbench
-- Wed Jun 14 14:44:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema diariodigital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diariodigital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diariodigital` DEFAULT CHARACTER SET utf8 ;
USE `diariodigital` ;

-- -----------------------------------------------------
-- Table `diariodigital`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diariodigital`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `nick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `diariodigital`.`anotacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diariodigital`.`anotacoes` (
  `idanotacoes` INT NOT NULL AUTO_INCREMENT,
  `grenciamento` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `usuario_nick` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idanotacoes`, `grenciamento`),
  INDEX `fk_Anotacoes_usuario_idx` (`usuario_id` ASC, `usuario_nick` ASC) VISIBLE,
  CONSTRAINT `fk_Anotacoes_usuario`
    FOREIGN KEY (`usuario_id` , `usuario_nick`)
    REFERENCES `diariodigital`.`usuario` (`id` , `nick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `diariodigital`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diariodigital`.`feedback` (
  `idFeedback` INT NOT NULL,
  `feed` TEXT NOT NULL,
  `usuario_id` INT NOT NULL,
  `usuario_nick` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFeedback`),
  INDEX `fk_Feedback_usuario1_idx` (`usuario_id` ASC, `usuario_nick` ASC) VISIBLE,
  CONSTRAINT `fk_Feedback_usuario1`
    FOREIGN KEY (`usuario_id` , `usuario_nick`)
    REFERENCES `diariodigital`.`usuario` (`id` , `nick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into usuario (nick, senha) values ("Pedro","123456");


select *from feedback;